export const userData = [
  {
    id: 1,
    name: "Alice",
    email: "alice@example.com",
    role: "Admin",
    status: "Active",
  },
  {
    id: 2,
    name: "Bob",
    email: "bob@example.com",
    role: "Merchant",
    status: "Inactive",
  },
  {
    id: 3,
    name: "Charlie",
    email: "charlie@example.com",
    role: "Member",
    status: "Pending",
  },
  {
    id: 4,
    name: "David",
    email: "david@example.com",
    role: "Admin",
    status: "Active",
  },
  {
    id: 5,
    name: "Eva",
    email: "eva@example.com",
    role: "Merchant",
    status: "Active",
  },
  {
    id: 6,
    name: "Frank",
    email: "frank@example.com",
    role: "Member",
    status: "Inactive",
  },
  {
    id: 7,
    name: "Grace",
    email: "grace@example.com",
    role: "Admin",
    status: "Pending",
  },
  {
    id: 8,
    name: "Henry",
    email: "henry@example.com",
    role: "Merchant",
    status: "Active",
  },
  {
    id: 9,
    name: "Ivy",
    email: "ivy@example.com",
    role: "Member",
    status: "Active",
  },
  {
    id: 10,
    name: "Jack",
    email: "jack@example.com",
    role: "Admin",
    status: "Inactive",
  },
  {
    id: 11,
    name: "Karen",
    email: "karen@example.com",
    role: "Merchant",
    status: "Pending",
  },
  {
    id: 12,
    name: "Leo",
    email: "leo@example.com",
    role: "Member",
    status: "Active",
  },
  {
    id: 13,
    name: "Mia",
    email: "mia@example.com",
    role: "Admin",
    status: "Active",
  },
  {
    id: 14,
    name: "Nora",
    email: "nora@example.com",
    role: "Merchant",
    status: "Inactive",
  },
  {
    id: 15,
    name: "Oscar",
    email: "oscar@example.com",
    role: "Member",
    status: "Pending",
  },
];
